from enum import Enum


class UserRole(str, Enum):
    """Role names used by both auth and role-aware UI decisions."""

    ADMIN = "admin"
    OPERATOR = "operator"
    VIEWER = "viewer"


class AssetType(str, Enum):
    """Operational entity types visible in the common operating picture."""

    PERSONNEL = "personnel"
    VEHICLE = "vehicle"
    SENSOR = "sensor"
    GATEWAY = "gateway"


class AssetStatus(str, Enum):
    """High-level asset health state used for badges and filtering."""

    NOMINAL = "nominal"
    WATCH = "watch"
    ALERT = "alert"
    OFFLINE = "offline"


class EventType(str, Enum):
    """Event categories generated by sensors, personnel, vehicles, and systems."""

    ACCESS_DENIED = "access_denied"
    GEOFENCE_BREACH = "geofence_breach"
    EQUIPMENT_OFFLINE = "equipment_offline"
    TEMPERATURE_THRESHOLD = "temperature_threshold"
    SENSOR_HEARTBEAT = "sensor_heartbeat"
    ROUTE_DEVIATION = "route_deviation"


class Severity(str, Enum):
    """Shared severity scale for events and incidents."""

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class IncidentStatus(str, Enum):
    """Lifecycle states operators can reason about during triage."""

    OPEN = "open"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
